internal/ssh/handler.go

Fix for reconnecting.

---

internal/ssh/handler.go

This is a fix to make sure we properly and cleanly disconnect and
cleanup ssh sessions.

Proper SSH disconnect

---

cmd/connect.go
cmd/socket.go

check for empty strings and make sure when no valid email or domain is
provided then exit with code 1, user would never be able to access that
socket as no valid emails or domain would pass the authz flow

improved use-ability

---

cmd/client.go
cmd/root.go
go.mod
go.sum

~~Currently, the destination host for the TLS connection is hardcoded with the US IP.
Once the proxy issue is fixed on the server-side we can remote this.~~

feat: add client commands

---

cmd/connect.go
cmd/root.go
cmd/socket.go
internal/http/models.go

Adding new commnand to show all socket info.
Also now including the SSH CA when it's a TLS socket with cloudauth
enabled.
broke out the socket info table, to root.go and have it called from
socket create, socket show, as well as connect
less code duplication :)

Adding new command, mysocketctl socket show

---

Makefile
internal/http/handler.go

adding build and upgrade code for arm osarch

ARM 32bit support

---

cmd/connect.go
cmd/root.go
cmd/socket.go

Adding support for SSH sockets. SSH sockets are proxied by out SSH
proxy and all Sessions are recorded and can be replayed in the portal
Pretty cool :)

Support for SSH sockets

---

Makefile
cmd/client.go
cmd/client_unix.go
cmd/client_windows.go
go.sum

Builds for windows will now succeeed, resize for windows not quite done
Also included go mod tidy in Make
need to fix static username later

fix resize for windows

---

Makefile
internal/http/handler.go

Would like to use this on my M1 mac.

add support for MacOS on arm64

---

cmd/login.go
cmd/root.go
go.mod
go.sum
internal/http/handler.go
internal/http/models.go

- adding ability to users log in with SSO

feat: login with SSO

---

cmd/login.go
go.mod
go.sum
internal/http/handler.go

- improving api error handling
- added retries if for some unknown reasons the api is not working

Improving error handling in device auth flow

---

cmd/connector.go
internal/api/api.go
internal/api/models/socket.go
internal/connector/config/config.go
internal/connector/config/config_test.go
internal/connector/core/core.go
internal/connector/service.go
internal/logging/logger.go

- pass the ctl version to the api
- remove the stacktrace and caller keys from logs
- validate the connector name
- add more scenarios to socket name sanitizer

Improve logs and validations

---

go.mod
internal/api/api.go
internal/connector/core/core.go
internal/ssh/connect.go

- add a retry to tunnels, this should resolve some problems related for static sockets
- try to find the access token from env for retro compatibility

Improve realiability with tunnel connections

---

internal/connector/discover/docker.go
internal/connector/discover/ec2.go

Fix with parsing out tahs and labels correctlty

Fixing issue with parsing docker labels and ec2 tag

---

internal/api/api.go

This caused the tunnel connect command to fail, fixing this

Fixing API URL

---

client/preference/data.go
client/preference/preference.go
cmd/client.go
cmd/client/db/db.go
cmd/client/db/dbeaver.go
cmd/client/db/mycli.go
cmd/client/db/mysql.go
cmd/client/db/mysql_workbench.go
cmd/client/ssh/ssh.go
internal/client/client.go
internal/client/resources.go

Record, retrieve and suggest socket username, db name and client, along with logged in client orgs.

Keep track of user preference history

---

internal/http/server.go

improved the default webpage for the built-in webserver

Internal webserver love

---

internal/connector/core/core.go
internal/connector/discover/discover.go
internal/connector/discover/docker.go
internal/connector/discover/ec2.go
internal/connector/discover/k8.go
internal/connector/discover/networkscan.go
internal/connector/discover/static_sockets.go

- connector should not delay when it first run

[Improvement] avoid initial delays in connector

---

cmd/tunnel.go

deprecating --localssh, now its --sshserver , so similar as --httpserver use --sshserver instead

use --sshserver instead of localssh

---

cmd/connect.go
cmd/socket.go

No more need to check for auth emails

---

Makefile
internal/api/api.go
internal/client/client.go
internal/http/handler.go
internal/ssh/connect.go
internal/ssh/handler.go

Updating API and Tunnel end points

Updating API and Tunnel end points

---

.github/workflows/manual-go.yml

We are adding manual build and release action

FEAT: manual build and release Action

---

cmd/policy.go
go.mod
go.sum
internal/api/models/policy.go

adding version, removing what{}
also some template improvements
removing border when printing policy
adding color printing of json

Improved policy handling

---

internal/api/api.go
internal/api/models/socket.go
internal/connector/config/config.go
internal/connector/core/core.go
internal/connector/core/policy_handler.go
internal/connector/core/policy_manager.go
internal/connector/discover/ec2.go
internal/connector/discover/k8.go
internal/connector/discover/networkscan.go
internal/connector/discover/static_sockets.go
mocks/api_mock.go

- now users can attach policies in the connector using the policies names in mysocket.yaml config file

[feat] add policies to connector
